### PR TITLE
Initial support for Android Gradle projects

### PR DESCRIPTION
**Pull request by cbruegg**
Summary of changes:

- `buildClassPath()` results are now cached (otherwise they are computed twice)
- Moved some code related to Gradle to a dedicated class
- Added support for locating AARs
- Added detection of Android SDK location (checks environment variables, `local.properties`, most common paths on Win/Mac/Lin)
- Fix: `workspaceClassPath()` now also considers built class files of subprojects
- Removed some files from repo that should be ignored
- Added test projects

One test project is using the Google Maven Repository. Another test project is using the local Maven repository within the Android SDK.

### CODE REVIEW

**Comment by cbruegg** [comment]
The build fails on CI due to this: `SDK location not found. Define location with sdk.dir in the local.properties file or with an ANDROID_HOME environment variable.`

Interestingly, this issue doesn't happen on my machine. I'll investigate.

**Comment by cbruegg** [comment]
Ah, this of course is because the current Travis environment contains no Android SDK. I'll try and fix that.

**Comment by cbruegg** [comment]
Fixed! Tests are now passing.

**Comment by cbruegg** [comment]
Update: This now supports the old Android project style that uses the locally installed Maven repo within the Android SDK directory. I've added a test for it as well.

**Comment by cbruegg** [comment]
Did you close this by accident?

**Comment by linghuiluo** [comment]
> Did you close this by accident?

I have merged it

**Comment by cbruegg** [comment]
Oh, I see. However `develop` only has the commits up to "Fix index of matcher.group", have you merged the other commits locally?

**Comment by linghuiluo** [comment]
> Oh, I see. However `develop` only has the commits up to "Fix index of matcher.group", have you merged the other commits locally?

oh, i forgot to push

**Comment by linghuiluo** [comment]
thanks for checking!

**Pull request closed without merging**
